meta_product_name: "Rainbow Heroes"
meta_title: "Rainbow Heroes - 5555 NFT's fighting for love on Solana blockchain."
meta_description: "5555 NFT's fighting for love on solana blockchain. Hand drawn."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@RainbowHeroesNFT"   # required for Twitter Cards
